before:
  hooks:
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  main: main.go
  binary: mac-cleanup
  goos:
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  - s390x
  - ppc64le
  goarm:
  - 5
  - 6
  - 7
  ignore:
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: ppc64le
    - goos: darwin
      goarch: s390x
  flags:
  - -trimpath
  ldflags:
  - -s -w

archives:
  - format_overrides:
    replacements:
      darwin: mac
checksum:
  algorithm: sha512

release:
  github:
    owner: mac-cleanup
    name: mac-cleanup
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
    - '^chore:'
    - '^ci:'
    - '^docs?:'
    - '^readme:'
    - '^tests?:'
    - '^\w+\s+'
